version: "3"

services:
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  thumbor:
    image: ghcr.io/minimalcompact/thumbor
    ports:
      - "80:80"
    environment:
      - UPLOAD_ENABLED=True
      - THUMBOR_NUM_PROCESSES=0
      - RESULT_STORAGE_STORES_UNSAFE=False
      - RESULT_STORAGE=thumbor.result_storages.file_storage
      - STORAGE=thumbor.storages.file_storage

  express:
    image: express:latest
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - THUMBOR_HOST=thumbor
      - THUMBOR_PORT=80
      - TORNADO_HOST=127.0.0.1
    depends_on:
      - redis
      - thumbor
