openapi: 3.0.3
info:
  title: Image Processing API
  description: API for handling image processing via a job queue.
  version: 1.0.0
paths:
  /job:
    post:
      summary: Add an image processing job to the queue and immediately start it
      parameters:
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
            enum:
              - image/jpg
              - image/png
      requestBody:
        description: Image data to be processed
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: Job created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The ID of the created job.
                  status:
                    type: string
                    description: The initial status of the job.
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /job/{id}:
    get:
      summary: Get the status of a specific job
      parameters:
        - name: id
          in: path
          description: Job ID
          required: true
          schema:
            type: string
      responses:
        200:
          description: Job status retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: The current status of the job.
        404:
          description: Job not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Job status retrieval failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /jobs:
    get:
      summary: Retrieve a list of all jobs
      responses:
        200:
          description: A list of jobs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Job ID
                    status:
                      type: string
                      description: Job processing status
                      enum:
                        - completed
                        - failed
                        - delayed
                        - active
                        - waiting
                        - waiting-children
                        - unknown
        500:
          description: Job list retrieval failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
